name = "rsc"
type = "javascript"
compatibility_date = "2022-01-16"
compatibility_flags = ["streams_enable_constructors"]
workers_dev = true

[site]
bucket = "./dist/client"
entry-point = "./dist/server"
exclude = ["*.json", "*.html"]

[build]
command = "pnpm run build:client && pnpm run build:server:worker && cp wrangler/package.json dist/server"

[build.upload]
format = "service-worker"

[env.production]
route = "rsc.tosuke.me/*"
